# golangci-lint configuration for A+ Go Report Card grade
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck      # Checks for unchecked errors
    - gosimple      # Simplifies code
    - govet         # Examines Go source code and reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Advanced Go linter
    - typecheck     # Type-checks Go code
    - unused        # Checks for unused constants, variables, functions and types

    # Additional linters for A+ grade
    - gofmt         # Checks whether code was gofmt-ed
    - goimports     # Checks import statements are formatted
    - misspell      # Finds commonly misspelled English words
    - gocritic      # Provides diagnostics that check for bugs, performance and style issues
    - gocyclo       # Computes cyclomatic complexities
    - dupl          # Tool for code clone detection
    - gosec         # Inspects source code for security problems
    - unconvert     # Remove unnecessary type conversions
    - whitespace    # Detection of leading and trailing whitespace
    - goprintffuncname # Checks that printf-like functions are named correctly
    - goconst       # Finds repeated strings that could be constants
    - gocognit      # Computes cognitive complexities of functions
    - bodyclose     # Checks whether HTTP response body is closed
    - nilerr        # Finds code that returns nil even if it checks that the error is not nil
    - nolintlint    # Reports ill-formed or insufficient nolint directives
    - stylecheck    # Replacement for golint
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter
    - exportloopref # Checks for pointers to enclosing loop variables
    - sqlclosecheck # Checks that sql.Rows and sql.Stmt are closed
    - rowserrcheck  # Checks whether Err of rows is checked successfully
    - wastedassign  # Finds wasted assignment statements
    - predeclared   # Finds code that shadows one of Go's predeclared identifiers

  disable:
    - exhaustruct   # Too strict for practical use
    - varnamelen    # Can be too opinionated
    - gomnd         # Can be too strict about magic numbers

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120
    tab-width: 4

  goimports:
    local-prefixes: github.com/scttfrdmn/aperture

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
    dot-import-whitelist:
      - fmt
    http-status-code-whitelist: ["200", "400", "404", "500"]

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Exclude known linters from partially hard-vendored code
    - path: internal/third_party/
      linters:
        - gocritic
        - stylecheck
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
